server:
  port: 80

spring:
  application:
    name: zuul
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: localhost
    timeout: 1000


zuul:
  routes:
    user-service:
      path: /u/**
      url: http://localhost:8001
    product-service:
      path: /p/**
      serviceId: product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/


