spring:
  profiles:
    active: ${spring.profiles.active}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gankki
## 默认为true，表示动态代理为cglib，特殊，spring data jpa中使用的是jdk的动态代理
  aop:
    proxy-target-class: true
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.gankki.data.jpa.entity

server:
  tomcat:
    basedir: E:/gankkscode/gankkilog/tomcatlog

mavensettings: @testsettings@
testprofie: testprofile public
testdev: default

---
spring:
  profiles: prod

testdev: prod
testprofie: testprofile prod

