server:
  port: 7001

spring:
  application:
    name: product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/

ribbon:
  eureka:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
