server:
     port: 6068


spring:
    kafka:
        bootstrap-servers: 127.0.0.1:9092
        consumer:
            auto-commit-interval: 100
            auto-offset-reset: earliest
            enable-auto-commit: true
            group-id: testGroup
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            acks: 1
            batch-size: 16384
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            retries: 0
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    application:
        name: kafka
